### ISSUE TITLE
New feature: persist selected fan speed for each mode

### ISSUE THREAD

**Issue by 35gh** [sicknesz/midea-inventor-card#7]
It will be good to persist the selected fan speed for each mode (for the modes for which it can be selected, i.e. target, smart, continuous).

Current behaviour:
1. Select Continuous mode and fan speed "low"
2. Select Dryer mode. The fan speed is set to "high" (forced fan speed for "Dryer" mode)
3. Select Continuous mode back, the fan speed remains on "high"

Expected behaviour:

3. Select Continuous mode back, the fan speed is restored to the previous selected speed for that mode ("low" in this example) 

Thanks!

**Comment by sicknesz** [comment]
Im not the one to ask for this, it's the integration that control the appliciances i only "show" the information from the integration, you should ask here : https://github.com/nbogojevic/midea-beautiful-air, im closing this because i have no control over this.

Kind regards,
sicknesz

PS/Edit : If you modify the automation code provided there : https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan you can also do that yourself and have homeassistant set the proper fan mode for you
